Index/urls.py
from django.urls import path, include

from Index import views

app_name = "Index"

urlpatterns = [
    path('', views.index.as_view() ,name="index"),  
    path('RecomendationWrite/', views.RecomendationWrite.as_view() ,name="RecomendationWrite"),  
    path('Contact/', views.Contact.as_view() ,name="Contact"),  
    path('AllProjects/', views.AllProjects.as_view() ,name="AllProjects"),  
    
   
    
]

Portfolio/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),  #userName:rohan   #pwd :- 12345geek
    path('', include('Index.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/All_projects.html
{% extends "base.html" %}
{% load static %}



{% block title %}Rohan Sadhukhan{% endblock %}



{% block add_css %}
 <style>
     .imgShdw{
         filter: drop-shadow(5px 5px 5px gray);
     }

     .card-hlight {
   box-shadow: 0 2px 3px 0 rgba(0, 0, 0, 0.2), 0 3px 10px 0 rgba(0, 0, 0, 0.19);

}

.card-hlight:hover {
   box-shadow: 0 20px 25px 0 rgba(0, 0, 0, 0.2), 0 20px 25px 0 rgba(0, 0, 0, 0.19);

}
 </style>
{% endblock %}





{% block content %}

 
<!-- Project section -->
<div class="container text-center my-5 pt-5" id="project">
    <h1 class="font-weight-light">My <span class="text-primary font-weight-bold">Projects</span></h1>
    
        <div class="row my-5  ">

            {%for P in project%}
            
            <!-- first col -->
            <div class="col-12 col-md-4 my-2">
                <div class="card shadow h-100">
                    <img class="card-img-top p-1" src="{{P.image.url}}"   alt="image">
                    <div class="card-body">
                        <h4>{{P.ProjectName}}</h4>
                        <p class="card-text">{{P.ProjectDescribtion|truncatechars:30}}</p>
                        <a href="javascript:void(0)" data-toggle="modal" data-target="#projectModal{{forloop.counter}}" class="stretched-link" style="text-decoration: none;">More</a>
                    </div>
                    
                </div>
            </div>
         

                        <!-- Large modal -->
            <div class="modal fade bd-example-modal-lg" id="projectModal{{forloop.counter}}" tabindex="-1" role="dialog" aria-labelledby="myLargeModalLabel" aria-hidden="true">
            <div class="modal-dialog modal-lg">
                <div class="modal-content text-justify-center">
                    <img class=" w-100 p-2" src="{{P.image.url}}"  height="300px" alt="image">
                   <h5 class="mt-3">{{P.ProjectName}}</h5> 
                   <p class="card-text mt-2">{{P.ProjectDescribtion}}</p>
            <div class="  py-3"> <a href="{{P.ProjectLink}}" class="btn btn-outline-primary py-1" > Project Link  </a></div>
                </div>
            </div>
            </div>
            {%endfor%}
            
        
        </div>

        


</div>





{% endblock %}
 




  {% block add_js %}
    {% endblock %}

templates/Contact.html
{% extends "base.html" %}
{% load static %}



{% block title %}Rohan Sadhukhan{% endblock %}



{% block add_css %}
 <style>
     .imgShdw{
         filter: drop-shadow(5px 5px 5px gray);
     }

     .card-hlight {
   box-shadow: 0 2px 3px 0 rgba(0, 0, 0, 0.2), 0 3px 10px 0 rgba(0, 0, 0, 0.19);

}

.card-hlight:hover {
   box-shadow: 0 20px 25px 0 rgba(0, 0, 0, 0.2), 0 20px 25px 0 rgba(0, 0, 0, 0.19);

}
 </style>
{% endblock %}





{% block content %}

 <div class ="container my-5 py-5" id="ContactID">
            <h1 class ="font-weight-light text-center py-5">
              <span class ="font-weight-bold text-primary">Thank you!</span>
              for your interest
            </h1>
            <div class ="row justify-content-center">
              <div class ="col-11 col-lg-5">
                <form method="POST" action="{%url 'Index:Contact'%}" >
                  {%csrf_token%}
                  <div class ="form-group">
                    <label for="name">Name *</label>
                    <input name="name" type="text" id="name" class ="form-control shadow"  required/>
                  </div>

                  <div class ="form-group">
                    <label for="email">Email *</label>
                    <input name="email" type="email" id="email" class ="form-control shadow" required/>
                  </div>

                  <div class ="form-group">
                    <label for="describtion">Tell me about your project *</label>
                    <textarea name="Projectmsg" id="Msg" rows="5" class ="form-control shadow"  required></textarea>
                            </div>
                  <button type="submit" class ="btn btn-primary shadow float-right"> Let's Talk Business</button>
                  <div class ="py-5 mx-2 text-center">
                    <h5 class = "">{{subMsg}}</h5>
                  </div>
                  
                </form>
              </div>
            </div>
          </div>
{% endblock %}
 




  {% block add_js %}
    {% endblock %}

templates/Recomendation.html
{% extends "base.html" %}
{% load static %}



{% block title %}Rohan Sadhukhan{% endblock %}



{% block add_css %}
 <style>
     .imgShdw{
         filter: drop-shadow(5px 5px 5px gray);
     }

     .card-hlight {
   box-shadow: 0 2px 3px 0 rgba(0, 0, 0, 0.2), 0 3px 10px 0 rgba(0, 0, 0, 0.19);

}

.card-hlight:hover {
   box-shadow: 0 20px 25px 0 rgba(0, 0, 0, 0.2), 0 20px 25px 0 rgba(0, 0, 0, 0.19);

}
 </style>
{% endblock %}





{% block content %}

 <div class="container my-5 py-5"  id="RecomID">
            <h1 class="font-weight-light text-center py-5">
              <span class="font-weight-bold text-primary">Thank you! </span>
               for your time
            </h1>
            <div class="row justify-content-center">
              <div class="col-11 col-lg-5">
                <form method="POST" action="{%url 'Index:RecomendationWrite'%}">
                  {%csrf_token%}
                  <div class="form-group">
                    <label for="name">Name *</label>
                    <input name="name" type="text" id="name" class="form-control shadow"   />
                  </div>

                  <div class="form-group">
                    <label for="email">Email *</label>
                    <input name="email" type="email" id="email" class="form-control shadow"   />
                  </div>

                  <div class="form-group">
                                <label for="Company_Institution">Company/Institution *</label>
                    <input name="Company_Institution" type="text" id="Company_Institution" class="form-control shadow"   />
                            </div>
                            
                             <div class="form-group">
                    <label for="Designation">Designation *</label>
                    <input name="Designation" type="text" id="Designation" class="form-control shadow"   />
                  </div>

                  <div class="form-group">
                    <label for="Recomendation">Recomendation *</label>
                    <textarea name="Recomendation" id="Recomendation" rows="5" class="form-control shadow" ></textarea>
                            </div>
                  <button  type="submit" class="btn btn-danger shadow float-right"> Lots Of Love!</button>
                  <div class="py-5 mx-2 text-center">
                    <h5 class="text-success" >{{subMsg}}</h5>
                  </div>
                  
                </form>
              </div>
            </div>
          </div>
{% endblock %}
 




  {% block add_js %}
    {% endblock %}

templates/base.html
<!doctype html>
<html lang="en">

<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css"
        integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">

         <!-- Font Awsome -------------------------------------------------------------------------------------------->
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.css">
   
   <!-- Fontawsome css -->
   <link href="/static/css/all.css" rel="stylesheet">
   <!--load all styles -->
   <link href="fontawesome.css" rel="stylesheet">
   <link href="brands.css" rel="stylesheet">
   <link href="solid.css" rel="stylesheet">
   <link href="regular.css" rel="stylesheet">
   <link href="svg-with-js.css" rel="stylesheet">
   <link href="v4-shims.css" rel="stylesheet">

  

    <title>{% block title %}{% endblock %}</title>


    {% block add_css %}
    
    {% endblock %}



    <style>
        
  .scrol::-webkit-scrollbar {
  width: 2px; 
  height: 5px;              /* width of the entire scrollbar */
}

.scrol::-webkit-scrollbar-track {
  background: transparent;        /* color of the tracking area */
}

.scrol::-webkit-scrollbar-thumb {
  background-color: #0064ff;    /* color of the scroll thumb */
  border-radius: 10px;       /* roundness of the scroll thumb */
  border: 3px solid transparent;  /* creates padding around scroll thumb */
}


.contact {
    display: inline;
  }
  .contact2{
      display: none;
  }

@media only screen and (max-width: 769px) {
  .contact {
    display: none;
  }
  .contact2{
      display: inline;
  }
}
    </style>

</head>

<body>



<!-- navbar section -->
 <nav class="navbar navbar-expand-md fixed-top bg-white shadow">
 


    <div class="container my-2">
        <a href="/" class="navbar-brand text-primary font-weight-bold ">
        Rohan Sadhukhan
        </a>
        <!-- contact button -->
        <a href="{%url 'Index:Contact'%}" class="ml-auto contact"> <button class="btn btn-outline-info  mx-3">Contact Me</button></a> 
        

        <!-- nav items -->
        <button class="navbar-toggler" data-toggle="collapse" data-target="#collapseNav">
            <span class="fas fa-bars text-primary"></span>
        </button>

        <div class="collapse navbar-collapse flex-grow-0" id="collapseNav">
            
        <div class="navbar-nav ">
        <!--  <center> <div class="bg-primary my-1" style=" width: 50%; height: 1px;"></div></center> -->

      

        <a href="/" class="nav-item nav-link h6 text-primary my-auto text-center my-3 ">Home</a>

        <a href="#about" class="nav-item nav-link h6 text-primary my-auto text-center my-3 ">About</a>
        
            <a href="#project" class="nav-item nav-link h6 text-primary my-auto text-center my-3"> Project's</a>
        
            <a href="#Tstack" class="nav-item nav-link h6 text-primary my-auto text-center my-3">Tech Stack</a>

            <a href="#Tstack" class="nav-item nav-link h6 text-primary my-auto text-center my-3">Experience</a>

              <a href="{%url 'Index:Contact'%}" class="nav-item nav-link h6 text-primary my-auto text-center my-3 contact2"> <button class="btn btn-outline-info  mx-3">Contact Me</button></a> 

           
        </div>

        </div>
         <!-- nav items end-->

    </div>




 </nav>


 






      {% block content %}

      {% endblock %}








<!-- Footer -->
<footer>
    <div class="container-fluid bg-primary text-center">


        <!-- first row -->
        <div class="row py-5">
            <div class="col-12">
                <h2 class="text-light">Interested in working with me?</h2>
              <a href="{%url 'Index:Contact'%}">  <button class="btn btn-outline-light btn-lg">Let's Talk</button> </a>
            </div>
        </div>


        <!-- second row -->
        <div class="row">
            <!-- col 1 -->
            <div class="col-12 col-md-4 py-3 pb-3">
                <h5 class="text-light mb-3 " >More Links</h5>
                <a class="text-light d-block" href="/" style="text-decoration: none;">Home</a>
                <a class="text-light d-block" href="{%url 'Index:Contact'%}" style="text-decoration: none;">Contact Me</a>
                <a class="text-light d-block" href="#project"  style="text-decoration: none;">Project's</a> 
                <a class="text-light d-block" href="{%url 'Index:RecomendationWrite'%}" style="text-decoration: none;">
                Write a recommendation <i class="fas fa-heart text-light"></i>
                </a>
            </div>
            <!-- col 2 -->
            <div class="col-12 col-md-4 py-3 text-light text-justify">
                <p>I am a Full Stack Web Developer who can deliver your projects using technologies like Html, CSS, JavaScript, Bootstrap, Django, ReactJs , MongoDB, Sql.</p>
            </div>
            <!-- col 3 -->
            <div class="col-12 col-md-4 py-3">
                 <h5 class="text-light mb-3" >Social</h5>
                 <center class="py-1"><a href="https://www.linkedin.com/in/rohan-sadhukhan/" target="_blank">
                     <i class="fab fa-linkedin text-light" style="height: 6%; width: 6%;"></i>
                 </a></center>
                 <center class="py-1"><a href="https://github.com/rohansadhukhan65" target="_blank">
                     <i class="fab fa-github text-light" style="height: 6%; width: 6%;"></i>
                 </a></center>
                <!--  <center class="py-1"><a href="#">
                     <i class="fas fa-envelope text-light" style="height: 6%; width: 6%;"></i>
                 </a></center> -->
            </div>
        </div>



        <!-- third row -->
        <div class="row">
           <div class="col-12 py-3 text-light text-justify ">
                <p class="text-light text-center">	 Copyright &#169;  Rohan Sadhukhan 2021</p>
            </div>
       </div>
    </div>
</footer>





    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"
        integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj"
        crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js"
        integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN"
        crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"
        integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV"
        crossorigin="anonymous"></script>


         <!-- javascript fontawsome -->
   <script defer src="/static/js/all.js"></script>
   <!--load all styles -->
   <script defer src="fontawesome.js"></script>
   <script defer src="brands.js"></script>
   <script defer src="solid.js"></script>
   <script defer src="conflict-detection.js"></script>
   <script defer src="regular.js"></script>
   <script defer src="v4-shims.js"></script>


      {% block add_js %}
    {% endblock %}
</body>

</html>

templates/index.html
{% extends "base.html" %}
{% load static %}



{% block title %}Rohan Sadhukhan{% endblock %}



{% block add_css %}
 <style>
     .imgShdw{
         filter: drop-shadow(5px 5px 5px gray);
     }

     .card-hlight {
   box-shadow: 0 2px 3px 0 rgba(0, 0, 0, 0.2), 0 3px 10px 0 rgba(0, 0, 0, 0.19);

}

.card-hlight:hover {
   box-shadow: 0 20px 25px 0 rgba(0, 0, 0, 0.2), 0 20px 25px 0 rgba(0, 0, 0, 0.19);

}


.techStackImg{
border-radius:100%;  background-color: aliceblue; padding: 2%; box-shadow: 0 10px 10px 0 rgba(0, 0, 0, 0.2), 0 10px 10px 0 rgba(0, 0, 0, 0.19);
}
 </style>
{% endblock %}





{% block content %}

 
<!-- Title Section -->
<div class="container">
    <div class="row text-center align-items-center my-5 py-5">
<!-- image -->
        <div class="col-12 col-md-6">
            <img class="img-fluid rounded-circle w-75 imgShdw" src="{{PersonalInfo.image.url}}" alt="Rohan">
        </div>
<!-- text -->
        <div class="col-12 col-md-6 pt-5">
            <div class="font-weight-light" style="font-size: 50px;">
            Hi, im <span class="text-primary">{{PersonalInfo.Name}}</span> 
            </div>
            
             <h4 class="font-weight-light">{{PersonalInfo.TagLine}}</h4>
             <h5 class="font-weight-light mt-5"> <i class="fas fa-mobile-alt"></i> {{PersonalInfo.PhoneNumber}}</h5>
             <h5 class="font-weight-light"> <i class="far fa-envelope"></i> {{PersonalInfo.Email}}</h5>
             <a href=" {{PersonalInfo.Resume.url}}" class="btn btn-outline-primary mt-3 " download="Rohan Sadhukhan"> Resume</a>
        </div>
      
    </div>
</div>












<!-- Recomendation stack section -->
<div class="container-fluid my-5">
    <!-- Row -->
    <div class="row text-center py-5 d-flex flex-nowrap overflow-auto scrollbar scrol">
       
       {%for recom in recomend%}
        <!-- Column -->
        <div class="col-12 col-md-4 "  data-toggle="modal" data-target="#RecomendationModal{{forloop.counter}}">
            <div class="card   h-100 card-hlight">
                <div class="card-body">
                    <h4 class="card-text  ">{{recom.RecomendationMsg|truncatechars:27}}</h4>
                    <p class="card-text text-secondary-mb-0    ">{{recom.Name}}</p>
                    <p class="card-text text-secondary ">{{recom.Designation}} at {{recom.CompanyName}}  </p>
                    
                </div>
            </div>
        </div>



        
                    
            <!-- Modal -->
            <div class="modal fade" id="RecomendationModal{{forloop.counter}}" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
            <div class="modal-dialog modal-dialog-centered" role="document">
                <div class="modal-content">
               
                <div class="modal-body">
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close"> 
                    <span aria-hidden="true">&times;</span>
                    </button>
                     <div class="text-justify-center mt-5">
                        <h5 class="card-text   font-weight-bold">{{recom.RecomendationMsg}}</h5>
                     </div>

                     <div class="text-center mt-2">
                        <div class="text-center">
                                <p class="  text-secondary pb-0 mb-0 font-weight-light"> {{recom.CompanyName}}  </p>
                                <p class="  text-secondary pb-0 mb-0 font-weight-light">{{recom.Designation}}</p>
                                <p class=" text-secondary font-weight-light">{{recom.Name}}</p>
                        </div>
                        
                    </div>

                </div>
                <!-- <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                    <button type="button" class="btn btn-primary">Save changes</button>
                </div> -->
                </div>
            </div>
            </div>
        {%endfor%}


 

    </div>
    <!-- End Row -->
</div>










<!-- Technology  Stack Section-->
<div class="bg-primary w-100 my-5" id="Tstack">

    <div class="container text-center py-5">
        <h1 class="font-weight-light text-light">
            <span class="text-light" style="font-weight: bold;">Technology  Stack</span> </h1>
            <div class="lead text-light" >i design, develope and deliver with these weapons </div>

            <!-- stack row -->
                    <div class="row justify-content-around py-3">

                        {%for stac in Tstack%}
            <!-- tech stack names start -->
                    <div class="col-3 mt-3">
                        <div class="text-center">
                        <img class="techStackImg"  src="{{stac.image.url}}"  height="70px" width="70px" alt="">
                            <br>
                            <span class="text-light text-center ">{{stac.StackName }}</span>
                        </div>
                        <div class="text-center">
                            {% if stac.Star1 %}
                            <span class="text-light">★</span>
                            {%else%}
                            <span class="text-dark">★</span>
                            {%endif%}
                            
                            {% if stac.Star2 %}
                            <span class="text-light">★</span>
                            {%else%}
                            <span class="text-dark">★</span>
                            {%endif%}

                            {% if stac.Star3 %}
                            <span class="text-light">★</span>
                            {%else%}
                            <span class="text-dark">★</span>
                            {%endif%}

                            {% if stac.Star4 %}
                            <span class="text-light">★</span>
                            {%else%}
                            <span class="text-dark">★</span>
                            {%endif%}

                            {% if stac.Star5 %}
                            <span class="text-light">★</span>
                            {%else%}
                            <span class="text-dark">★</span>
                            {%endif%}

                            {% if stac.Star6 %}
                            <span class="text-light">★</span>
                            {%else%}
                            <span class="text-dark">★</span>
                            {%endif%}

                        </div>
                    </div>
            <!-- tech stack names start end -->
                        {%endfor%}

            

                    </div> 
            <!-- stack row end-->

    </div>

</div>



<!-- Project section -->
<div class="container text-center my-5" id="project">
    <h1 class="font-weight-light">My <span class="text-primary font-weight-bold">Projects</span></h1>
    <div class="lead">I build websites just like these website</div> 
 <div class="row my-5 pt-3">

    {%for P in project%}
    {%if forloop.counter <= 3%}
     <!-- first col -->
     <div class="col-12 col-md-4 my-2">
         <div class="card shadow h-100">
             <img class="card-img-top p-1" src="{{P.image.url}}"   alt="image">
             <div class="card-body">
                  <h4>{{P.ProjectName}}</h4>
                 <p class="card-text">{{P.ProjectDescribtion|truncatechars:30}}</p>
                  <a href="javascript:void(0)" data-toggle="modal" data-target="#projectModal{{forloop.counter}}" class="stretched-link" style="text-decoration: none;">More</a>
             </div>
             
         </div>
     </div>




     <!-- Large modal -->
            <div class="modal fade bd-example-modal-lg" id="projectModal{{forloop.counter}}" tabindex="-1" role="dialog" aria-labelledby="myLargeModalLabel" aria-hidden="true">
            <div class="modal-dialog modal-lg">
                <div class="modal-content text-justify-center">
                    <img class=" w-100 p-2" src="{{P.image.url}}"  height="300px" alt="image">
                   <h5 class="mt-3">{{P.ProjectName}}</h5> 
                   <p class="card-text mt-2 px-2">{{P.ProjectDescribtion}} </p>
            <div class="  py-3"> <a href="{{P.ProjectLink}}" class="btn btn-outline-primary py-1" > Project Link  </a></div>
                </div>
            </div>
            </div>
     {%endif%}
     {%endfor%}
   
 </div>

<div class="my-5 text-right">
    <a href="{%url 'Index:AllProjects'%}" style="text-decoration: none;">
        <h5>
            See My Projects <i class="fas fa-arrow-right align-middle"></i>
        </h5>
    </a>
</div>



</div>




<!-- About section -->
<div class="container-fluid bg-light text-center my-5" id="about">
 <h1 class="font-weight-light text-dark pt-3">
     {%for a in about%}
     {%if forloop.counter <= 1%}
        <span class="text-primary" style="font-weight: bold;">About</span> me </h1>
        <div class="lead text-dark" >{{a.TagLine}} </div>

<div class="container my-5">
        <!-- row 1 -->
        <div class="row  mx-5  ">
            <!-- What can i do? -->
           <div class="col-12 col-md-6 text-justify my-5">
                <h4 class="text-center">What can  i do?</h4>
               <p>  {{a.What_can_i_do}} 
                </p>
           </div>
            <!-- What am i doing currently? -->
             <div class="col-12 col-md-6 text-justify  my-5">
                <h4 class="text-center">What am i doing currently?</h4>
               <p>{{a.What_am_i_doing_currently}} 
                </p>
           </div>
        </div>
        <!-- End row 1 -->

        <!-- row 2 -->
        <div  class="row  mx-5 ">
            <!-- What do i belive in? -->
            <div class="col-12 col-md-6 text-justify my-5">
                <h3 class="text-center">What do i belive in?</h3>
                <p>{{a.What_do_i_belive_in}} </p>
            </div>
            <!-- How i can help you? -->
             <div class="col-12 col-md-6 text-justify my-5 ">
                <h3 class="text-center">How i can help you?</h3>
                <p>{{a.How_i_can_help_you}} </p>
            </div>
        </div>
        <!-- End row 2 -->
    </div>
    {%endif%}
    {%endfor%}
</div>

 




<!-- Education & Work Experience -->
<div class="container py-3" id="EE">
    <div class="row">
        <!-- Education Section -->
        <div class="col-12 col-md-6 mt-5">
            <div class="row">
                <div class="col-12">
                     <h1 class="text-center font-weight-light text-dark py-3">My <span class="text-primary" style="font-weight: bold;">Education</span>  </h1>
                     


                     {%for e in education%}
                     <!-- Education card -->
                    <div class="card mt-3 shadow">
                       <!--  <h5 class="card-header">Featured</h5> -->
                        <div class="card-body">
                            <h5 class="card-title mb-3 pb-1 font-weight-bold">{{e.NameOfInstitute}}</h5>
                            <p class="card-text text-primary pb-0 mb-0 font-weight-light">{{e.NameOfDegree}} </p>
                            <small class="card-text text-primary font-weight-light">{{e.StartToEndDate}}</small>
                           
                        </div>
                    </div>
                     <!-- Education card end -->
                     {%endfor%}



                  

                </div>
            </div>
        </div>
        <!-- Education Section end -->




        <!-- Work Experience Section -->
        <div class="col-12 col-md-6 mt-5">
            <div class="row">
                <div class="col-12">
                     <h1 class="text-center font-weight-light text-dark py-3"> <span class="text-primary" style="font-weight: bold;">Work</span> Experience  </h1>

                    <!-- Education card -->
                    {%for e in workexp%}
                        <div class="card mt-3 shadow">
                        <!--  <h5 class="card-header">Featured</h5> -->
                            <div class="card-body">
                                <h5 class="card-title mb-3 pb-1 font-weight-bold">{{e.NameOfCompany}}</h5>
                                <p class="card-text text-primary pb-0 mb-0 font-weight-light">{{e.NameOfPost}}</p>
                                <small class="card-text text-primary font-weight-light">{{e.StartToEndDate}}</small>
                            
                            </div>
                        </div>
                    {%endfor%}
                     <!-- Education card end -->


                </div>
            </div>
        </div>
        <!-- Work Experience Section end -->




    </div>
</div>


{% endblock %}
 




  {% block add_js %}
    {% endblock %}